# Generated by Django 3.2 on 2021-04-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_t',
            name='schoolName',
            field=models.CharField(max_length=50),
        ),
    ]
