# Generated by Django 3.1.7 on 2021-05-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prereqcourse_t',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registration_t',
            name='semester',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='section_t',
            name='semester',
            field=models.CharField(max_length=15),
        ),
    ]
