# Generated by Django 3.2 on 2021-05-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_t',
            name='year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='section_t',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
