# Generated by Django 3.1.7 on 2021-05-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spmapp', '0002_auto_20210518_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dean_t',
            name='endDate',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AlterField(
            model_name='dean_t',
            name='startDate',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AlterField(
            model_name='head_t',
            name='endDate',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AlterField(
            model_name='head_t',
            name='startDate',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AlterField(
            model_name='vc_t',
            name='endDate',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AlterField(
            model_name='vc_t',
            name='startDate',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
