# Generated by Django 3.2 on 2021-04-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spmapp', '0002_alter_school_t_schoolname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department_t',
            name='departmentName',
            field=models.CharField(max_length=50),
        ),
    ]
