# Generated by Django 3.2 on 2021-05-23 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spmapp', '0002_auto_20210522_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section_t',
            name='year',
        ),
    ]
