# Generated by Django 3.2 on 2021-05-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spmapp', '0003_remove_section_t_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_t',
            name='year',
            field=models.IntegerField(default=2020, null=True),
        ),
    ]
