# Generated by Django 3.2 on 2021-05-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spmapp', '0003_auto_20210518_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prereqcourse_t',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
