# Generated by Django 3.2 on 2021-05-19 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spmapp', '0004_alter_prereqcourse_t_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataentry2AddingAssessmentdata_T',
            fields=[
                ('assessmentName', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='dataentry2mappingPloToCo_T',
            fields=[
                ('courseID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('coNum', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='dataentry2AddingnewCourseinformation_T',
            fields=[
                ('courseID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('semester', models.CharField(max_length=15)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.section_t')),
            ],
        ),
        migrations.CreateModel(
            name='dataentry2AddingnEvalautionData_T',
            fields=[
                ('courseID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
                ('coNum', models.CharField(max_length=4)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.section_t')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spmapp.student_t')),
            ],
        ),
    ]
