# Generated by Django 3.2 on 2021-05-21 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spmapp', '0006_auto_20210519_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration_t',
            name='year',
        ),
        migrations.RemoveField(
            model_name='section_t',
            name='year',
        ),
    ]
